---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus
  namespace: istio-system
spec:
  host: prometheus-kube-prometheus-prometheus
  subsets:
  - name: v1
    labels:
      app: prometheus
